### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Anjay :v maaf nyasar

### CODE REVIEW

**Comment by MoveAngel** [comment]
@tomyprs25

**Comment by keselekpermen69** [comment]
@MoveAngel Awikwok

**Comment by MuhamadFajarGaray** [comment]
@tomyprs25 Ppk

**Comment by MuhamadFajarGaray** [comment]
@keselekpermen69 Pepek kau

**Comment by MuhamadFajarGaray** [comment]
@keselekpermen69 @M000cZ kau juga pepek

**Comment by Aoihara** [comment]
@MuhamadFajarGaray .str

**Comment by ghost** [comment]
Anying gw di fban

**Comment by MoveAngel** [comment]
not me .. dont blame me

**Pull request closed without merging**
