### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by Lexsugarbrew**

### CODE REVIEW

**Comment by remtzx** [comment]
@Lexsugarbrew mberrr

**Comment by MoveAngel** [comment]
hmm wait whut?

**Comment by ghost** [comment]
@MoveAngel Update teros

**Comment by remtzx** [comment]
@tomyprs25 no wut wut

**Comment by remtzx** [comment]
Hm

Pada tanggal Min, 29 Mar 2020 01.35, Tomy Prasetyo <notifications@github.com>
menulis:

**Comment by goodmeow** [comment]
@remtzx

**Comment by MuhamadFajarGaray** [comment]
@goodmeow go commit die

**Comment by MrMissx** [comment]
@MuhamadFajarGaray Wowowo

**Comment by ghost** [comment]
@MuhamadFajarGaray Ramenih

**Comment by gudmeong** [comment]
pasi ccd

**Comment by xixugi** [comment]
anjasss add more bak

**Comment by gudmeong** [comment]
@vincreator uwuu.. aa pilingg guddd layk a sutttt nananan pi de wow

**Comment by remtzx** [comment]
pa

Pada tanggal Sel, 14 Apr 2020 07.30, Harun Al Rasyid <
notifications@github.com> menulis:

**Comment by gudmeong** [comment]
@remtzx heeett ni pull masi di nganu ae bjir

**Comment by ghost** [comment]
@GudMeong Yang pull siapa

**Pull request closed without merging**
