### PR TITLE
Update pmpermit.py

### PR DESCRIPTION
**Pull request by arifap195**

### CODE REVIEW

**Comment by arifap195** [comment]
Thanks

**Comment by ghost** [comment]
@arifap195 Paanih

**Comment by arifap195** [comment]
Bukan apa apa kwkwkkw

**Comment by xixugi** [comment]
bergurau antum? @arifap195

**Comment by adekmaulana** [comment]
@vincreator Ngakak anjir

**Comment by ghost** [comment]
Close cok

**Comment by MoveAngel** [comment]
ok i take it

**Pull request closed without merging**
